ens_job_index:
    path:     /
    defaults: { _controller: "EnsJobeetBundle:Job:index" }
    methods:  GET

ens_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsJobeetBundle:Job:show" }
    methods:  GET
    requirements:
      id: \d+

ens_job_new:
    path:     /new
    defaults: { _controller: "EnsJobeetBundle:Job:new" }
    methods:  [GET, POST]

ens_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "EnsJobeetBundle:Job:edit" }
    methods:  [GET, POST]

ens_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "EnsJobeetBundle:Job:delete" }
    methods:  DELETE
    
ens_job_preview:
    path:     /{company}/{location}/{token}/{position}
    defaults: { _controller: "EnsJobeetBundle:Job:preview" }
    methods:  GET
    requirements:
      token: \w+